/**
 * Client for the Python quant HTTP bridge
 * (`EMA_Strategy/mcp/quant_server/http_bridge.py`).
 *
 * Ported from that repo's `apps/web/lib/quant.ts`. The bridge publishes its
 * tool manifest at `GET /tools`, derived by introspection from the same
 * functions the MCP server exposes. We turn that manifest straight into AI SDK
 * tools rather than re-declaring the schemas here: a tool added in Python
 * appears in the chat with no TypeScript change, and the two surfaces cannot
 * drift apart.
 *
 * Architecture principle: AI orchestrates, Python calculates. Nothing in this
 * file computes a number.
 *
 * Server-only. Every request goes through an auth-gated route handler, which
 * hands its caller to the bridge's common gate (Eve Phase 15):
 *   - `X-Eve-Internal: EVE_INTERNAL_SECRET` proves the call comes from this
 *     server (required once the engine sets the same secret);
 *   - `Authorization: Bearer <Supabase access token>` says which user it is
 *     for. The engine verifies it and scopes saved strategies to that user,
 *     and its PostgREST calls run under the same token, so RLS applies too;
 *   - `X-Eve-Surface: ui` marks calls a human made by clicking in the UI.
 *     Only those may reach UI-only tools such as archiving; the chat route
 *     never sends it, so the model cannot either.
 */

import { jsonSchema, tool, type ToolSet } from "ai";
import type { JSONSchema7 } from "@ai-sdk/provider";

export const BRIDGE_URL = process.env.QUANT_BRIDGE_URL ?? "http://127.0.0.1:8010";

/** Who a bridge call is for. Built by route handlers from the session. */
export type BridgeAuth = {
  /** The signed-in user's Supabase access token. */
  token?: string | null;
  /** "ui" only for calls a human triggered by clicking; never from chat. */
  surface?: "chat" | "ui";
  requestId?: string;
  model?: string;
};

export function bridgeHeaders(auth: BridgeAuth = {}): Record<string, string> {
  const headers: Record<string, string> = { "content-type": "application/json" };
  const secret = process.env.EVE_INTERNAL_SECRET;
  if (secret) headers["x-eve-internal"] = secret;
  if (auth.token) headers.authorization = `Bearer ${auth.token}`;
  if (auth.surface === "ui") headers["x-eve-surface"] = "ui";
  if (auth.requestId) headers["x-request-id"] = auth.requestId;
  if (auth.model) headers["x-eve-model"] = auth.model;
  return headers;
}

/** Shape of one entry in the bridge's `/tools` manifest. */
export type ToolManifestEntry = {
  name: string;
  description: string;
  /** JSON Schema, generated by the bridge from the Python signature. */
  parameters: JSONSchema7;
};

export type BridgeStatus = { ok: true; tools: number } | { ok: false; error: string };

/**
 * Tools with side effects: `download_month_data` calls the broker API,
 * `process_month_data` overwrites parquet under `data/processed/`.
 *
 * The bridge withholds these unless `QUANT_ALLOW_WRITE_TOOLS=1` — but once an
 * operator sets that flag they become visible to the model too. A system-prompt
 * instruction to "ask first" is not enforcement, so `buildTools` filters them
 * out unconditionally. They stay reachable only through an explicitly confirmed
 * call on the deterministic path.
 */
export const WRITE_TOOLS = [
  "download_month_data",
  "process_month_data",
  "validate_dataset",
] as const;

/**
 * Bridge tools the chat does not get directly. `validate_strategy_spec`
 * carries the full spec schema (~7 KB); `propose_strategy_spec` (lib/eve/tools)
 * calls it itself, so offering both would pay for that schema twice a turn.
 */
export const CHAT_HIDDEN_TOOLS = ["validate_strategy_spec"] as const;

/**
 * Read-only tools the deterministic path may call on behalf of the UI.
 *
 * An allowlist rather than a passthrough of `/tools/{name}`: the bridge has no
 * auth and a 300-second timeout, so the proxy decides what is reachable.
 */
export const READ_TOOLS = [
  "list_research_months",
  "get_historical_candles",
  "generate_signal",
  "run_backtest_signals",
  "compare_timeframes",
  "parameter_search",
  "walk_forward_test",
  "backtest_significance",
  "validate_parameter_search",
  // Strategy builder (Eve Phase 15): stateless spec tools.
  "describe_strategy_vocabulary",
  "validate_strategy_spec",
  "preview_strategy_signals",
  "backtest_strategy_spec",
  "strategy_significance",
] as const;

export type ReadTool = (typeof READ_TOOLS)[number];

export function isReadTool(name: string): name is ReadTool {
  return (READ_TOOLS as readonly string[]).includes(name);
}

/** Bridge reachability, for the status indicator. */
export async function bridgeStatus(): Promise<BridgeStatus> {
  try {
    const res = await fetch(`${BRIDGE_URL}/health`, {
      cache: "no-store",
      signal: AbortSignal.timeout(3000),
    });
    if (!res.ok) return { ok: false, error: `bridge returned ${res.status}` };
    const body = (await res.json()) as { tools?: number };
    return { ok: true, tools: body.tools ?? 0 };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : "unreachable" };
  }
}

export async function fetchManifest(): Promise<ToolManifestEntry[]> {
  const res = await fetch(`${BRIDGE_URL}/tools`, { cache: "no-store", headers: bridgeHeaders() });
  if (!res.ok) {
    throw new Error(
      `quant bridge /tools returned ${res.status}. Is it running on ${BRIDGE_URL}?`,
    );
  }
  const body = (await res.json()) as { tools: ToolManifestEntry[] };
  return body.tools;
}

/**
 * The bridge does no argument coercion — it passes the JSON body straight into
 * a Python signature. `{"limit": "5"}` therefore reaches `1 <= limit <= 200`
 * and raises `TypeError`, surfacing as an opaque 400. (That is the bug behind
 * the old agent tab's broken dataset button.)
 *
 * So coerce here, driven by the manifest's own JSON Schema rather than a
 * hand-kept list of field names.
 */
export function coerceArgs(
  args: Record<string, unknown>,
  schema: JSONSchema7 | undefined,
): Record<string, unknown> {
  const props = (schema?.properties ?? {}) as Record<string, JSONSchema7>;
  const out: Record<string, unknown> = {};

  for (const [key, raw] of Object.entries(args)) {
    if (raw === null || raw === undefined || raw === "") continue;
    const type = props[key]?.type;

    if (type === "integer" || type === "number") {
      const n = typeof raw === "number" ? raw : Number(raw);
      out[key] = Number.isFinite(n) ? (type === "integer" ? Math.trunc(n) : n) : raw;
    } else if (type === "boolean") {
      // Python truth-tests the raw value, so the string "false" would read as
      // true. Decide it here instead.
      out[key] =
        typeof raw === "boolean" ? raw : !/^(false|0|no|off)$/i.test(String(raw).trim());
    } else if (type === "string") {
      out[key] = String(raw);
    } else {
      out[key] = raw;
    }
  }
  return out;
}

/** Call one tool. Errors are RETURNED, never thrown — see `buildTools`. */
export async function callTool(
  name: string,
  args: Record<string, unknown>,
  auth: BridgeAuth = {},
): Promise<unknown> {
  let res: Response;
  try {
    res = await fetch(`${BRIDGE_URL}/tools/${name}`, {
      method: "POST",
      headers: bridgeHeaders(auth),
      body: JSON.stringify(args ?? {}),
      signal: AbortSignal.timeout(310_000),
    });
  } catch (err) {
    return {
      error:
        `Could not reach the quant engine at ${BRIDGE_URL}: ` +
        `${err instanceof Error ? err.message : String(err)}. ` +
        "Start it with: uv run python -m mcp.quant_server.http_bridge",
    };
  }

  const body = await res.json().catch(() => ({
    error: `quant bridge returned non-JSON (status ${res.status})`,
  }));

  // A 4xx from the bridge is usually the model's mistake (bad month, absent
  // parquet) and carries a message it can act on, so hand the message back as a
  // tool result instead of throwing. Throwing would abort the whole stream and
  // lose the chance to self-correct.
  if (!res.ok) {
    const b = body as { error?: string; issues?: unknown };
    return {
      error: b.error ?? `quant bridge error (status ${res.status})`,
      status: res.status,
      // JSON-Pointer paths for a bad strategy spec, so the caller can fix
      // exactly that field.
      ...(b.issues ? { issues: b.issues } : {}),
    };
  }
  return (body as { result?: unknown }).result ?? body;
}

/** True when `callTool` returned an error object rather than a result. */
export function isToolError(
  value: unknown,
): value is { error: string; status?: number; issues?: { path: string; message: string }[] } {
  return !!value && typeof value === "object" && "error" in value;
}

/**
 * Build the AI SDK tool set from the bridge manifest.
 *
 * `jsonSchema()` wraps the Python-derived schema without a zod re-declaration.
 * Write tools are dropped here regardless of what the bridge published.
 */
export function buildTools(manifest: ToolManifestEntry[], auth: BridgeAuth = {}): ToolSet {
  const tools: ToolSet = {};
  // The chat never claims the "ui" surface, whatever the caller passed.
  const chatAuth: BridgeAuth = { ...auth, surface: "chat" };
  for (const entry of manifest) {
    if ((WRITE_TOOLS as readonly string[]).includes(entry.name)) continue;
    if ((CHAT_HIDDEN_TOOLS as readonly string[]).includes(entry.name)) continue;
    tools[entry.name] = tool({
      description: entry.description,
      inputSchema: jsonSchema(entry.parameters),
      execute: async (args) =>
        callTool(
          entry.name,
          coerceArgs((args ?? {}) as Record<string, unknown>, entry.parameters),
          chatAuth,
        ),
    });
  }
  return tools;
}

/** Verdict from the bridge's numeric grounding check. */
export type GroundingReport = {
  grounded: boolean;
  total_claims: number;
  grounded_claims: number;
  ungrounded_claims: number;
  evidence_values: number;
  answer_sha256: string;
  summary: string;
  ungrounded: { value: number; text: string; line: number; context: string }[];
};

/**
 * Ask the bridge which numeric claims in `answer` trace to `toolResults`.
 *
 * Advisory. It reports; it does not block or rewrite an answer. Note this is
 * NOT one of the model's tools — it lives on its own bridge route precisely so
 * the model cannot call its own grader and tune an answer to pass.
 */
export async function checkGrounding(
  answer: string,
  toolResults: unknown[],
): Promise<GroundingReport> {
  const res = await fetch(`${BRIDGE_URL}/grounding/check`, {
    method: "POST",
    headers: bridgeHeaders(),
    body: JSON.stringify({ answer, tool_results: toolResults }),
    signal: AbortSignal.timeout(15_000),
  });
  if (!res.ok) throw new Error(`grounding check returned ${res.status}`);
  return (await res.json()) as GroundingReport;
}
