/**
 * Template-rendered plain-English summary of a spec.
 *
 * Mirrors `quant/strategies/spec/describe.py` word for word, so the summary
 * the form shows while you edit matches the one the engine returns (and the
 * one stored with each saved version). Generated by code, never by the
 * model: what the user reads and approves is exactly what runs.
 * `scripts/verify-strategy-spec.ts` pins the wording against golden strings
 * copied from the Python tests.
 */

import type { Condition, ConditionGroup, Operand, StrategySpec } from "./schema";
import { sidesOf } from "./schema";
import { INDICATORS, resolvedParams } from "./vocabulary";

const LEVEL_TEXT: Record<string, string> = {
  prev_day_high: "yesterday's high",
  prev_day_low: "yesterday's low",
  prev_day_close: "yesterday's close",
  session_open: "today's open",
  session_high: "today's high so far",
  session_low: "today's low so far",
  vwap: "VWAP",
};
const REF_TEXT: Record<string, string> = {
  prev_day_close: "yesterday's close",
  session_open: "today's open",
  prev_bar_close: "the previous bar's close",
};
const CMP_TEXT: Record<string, string> = {
  gt: "is above",
  gte: "is at or above",
  lt: "is below",
  lte: "is at or below",
  crosses_above: "crosses above",
  crosses_below: "crosses below",
};
const TF_TEXT: Record<string, string> = { "1m": "1-minute", "5m": "5-minute", "15m": "15-minute" };

/** Python's `f"{v:g}"`: 6 significant digits, trailing zeros trimmed. */
export function fmtG(v: number): string {
  if (!Number.isFinite(v)) return String(v);
  if (v === 0) return "0";
  const exp = Math.floor(Math.log10(Math.abs(Number(v.toPrecision(6)))));
  if (exp < -4 || exp >= 6) {
    const [mant, e] = v.toExponential(5).split("e");
    const m = mant.replace(/\.?0+$/, "");
    const n = Number(e);
    return `${m}e${n < 0 ? "-" : "+"}${String(Math.abs(n)).padStart(2, "0")}`;
  }
  return String(Number(v.toPrecision(6)));
}

export function operandText(op: Operand): string {
  let text: string;
  switch (op.kind) {
    case "const":
      return fmtG(op.value);
    case "indicator": {
      const def = INDICATORS[op.name];
      const args = Object.values(resolvedParams(op.name, op.params)).map(fmtG).join(",");
      const base = `${def.label}(${args})`;
      if (op.name === "macd") {
        const out = op.output ?? "line";
        text = { line: `${base} line`, signal: `${base} signal line`, hist: `${base} histogram` }[out] ?? base;
      } else if (op.name === "bbands") {
        const out = op.output ?? "mid";
        text = { upper: `upper ${base}`, mid: `middle ${base}`, lower: `lower ${base}` }[out] ?? base;
      } else {
        text = base;
      }
      break;
    }
    case "price":
      text = `the ${op.field}`;
      break;
    case "level":
      text = LEVEL_TEXT[op.name];
      break;
    case "change_pct":
      text = `the % change vs ${REF_TEXT[op.ref]}`;
      break;
  }
  const offset = op.offset ?? 0;
  if (offset) text += ` ${offset} bar${offset !== 1 ? "s" : ""} ago`;
  return text;
}

export function conditionText(cond: Condition): string {
  const lhs = operandText(cond.lhs);
  if (cond.cmp === "rising" || cond.cmp === "falling") {
    const n = cond.bars ?? 1;
    const verb = cond.cmp === "rising" ? "is rising" : "is falling";
    const span = n === 1 ? "vs the previous bar" : `over ${n} bars`;
    return `${lhs} ${verb} ${span}`;
  }
  if (!cond.rhs) return `${lhs} ${CMP_TEXT[cond.cmp]} …`;
  let rhs = operandText(cond.rhs);
  if (cond.lhs.kind === "change_pct" && cond.rhs.kind === "const") rhs = `${fmtG(cond.rhs.value)}%`;
  return `${lhs} ${CMP_TEXT[cond.cmp]} ${rhs}`;
}

export function groupText(group: ConditionGroup | null | undefined): string {
  if (!group || (!group.all.length && !group.any.length)) return "";
  const parts: string[] = [];
  if (group.all.length) parts.push(group.all.map(conditionText).join(" and "));
  if (group.any.length) {
    const anys = group.any.map(conditionText);
    parts.push(anys.length === 1 ? anys[0] : "any of: " + anys.join("; "));
  }
  return parts.join(", and ");
}

function riskText(spec: StrategySpec): string[] {
  const r = spec.risk;
  const out: string[] = [];
  const v = (x: number | null) => fmtG(x ?? 0);
  const stop: Record<string, (x: number | null) => string> = {
    pct: (x) => `Stop-loss ${v(x)}% from entry.`,
    points: (x) => `Stop-loss ${v(x)} points from entry.`,
    atr: (x) => `Stop-loss ${v(x)} x ATR from entry.`,
  };
  const target: Record<string, (x: number | null) => string> = {
    pct: (x) => `Target ${v(x)}% from entry.`,
    points: (x) => `Target ${v(x)} points from entry.`,
    atr: (x) => `Target ${v(x)} x ATR from entry.`,
    r_multiple: (x) => `Target ${v(x)}R (x the stop distance).`,
  };
  out.push(r.stop.mode !== "none" ? stop[r.stop.mode](r.stop.value) : "No stop-loss.");
  if (r.target.mode !== "none") out.push(target[r.target.mode](r.target.value));
  if (r.trail.mode === "atr") out.push(`Trailing stop ${v(r.trail.value)} x ATR.`);
  else if (r.trail.mode === "breakeven_then_atr")
    out.push(`Stop moves to breakeven at 1R, then trails ${v(r.trail.value)} x ATR.`);
  if (r.time_stop_bars) out.push(`Exit after ${r.time_stop_bars} bars in the trade.`);
  return out;
}

export function describeSpec(spec: StrategySpec): string {
  const direction = { long_only: "Long-only", short_only: "Short-only", both: "Long-and-short" }[
    spec.direction
  ];
  const sides = sidesOf(spec.direction);
  const lines = [`${direction} NIFTY futures strategy on ${TF_TEXT[spec.timeframe]} bars.`];
  if (sides.includes("long")) {
    lines.push(`Buy when ${groupText(spec.entry.long)}.`);
    const ex = spec.exit.long;
    if (ex && (ex.all.length || ex.any.length)) lines.push(`Exit the long when ${groupText(ex)}.`);
  }
  if (sides.includes("short")) {
    lines.push(`Sell short when ${groupText(spec.entry.short)}.`);
    const ex = spec.exit.short;
    if (ex && (ex.all.length || ex.any.length)) lines.push(`Cover the short when ${groupText(ex)}.`);
  }
  lines.push(...riskText(spec));
  const s = spec.session;
  let window = `New entries ${s.entry_start}-${s.entry_end}`;
  window += s.eod_squareoff ? `; square off at ${s.squareoff_time}.` : "; positions may be held overnight.";
  lines.push(window);
  const lots = spec.sizing.lots;
  lines.push(`${lots} lot${lots !== 1 ? "s" : ""}, ${spec.execution.slippage} slippage.`);
  return lines.join(" ");
}
